version: '3.5'

services:

  app:
    build:
      context: app
      network: host
    environment:
      - FLASK_DEBUG=1  
      - PORT=80
    network_mode: host
    volumes:
      - ./app:/app
      - ./db:/db